### ISSUE TITLE
Lien vers la commande depuis la page du parc du client

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/B2B2C#12]
- ClientWeb/Park.aspx
- Pour un véhicule, cliquer sur l'icône des pièces commandées.
- Des liens vers ces pièces sont affichées.
- On souhaiterait plutôt un lien vers la commande ainsi que la date de la commande.

**Comment by jlenormant** [comment]
Est-ce que les deux ne serait pas mieux ? un lien plus discret vers la pièce, et un lien principal vers la commande (en affichant son n° et sa date).

Je crois que commander à nouveau une pièce à partir de la page commande n'est pas très simple.

**Comment by MamboJoel** [comment]
Oui, les deux c'est mieux en effet.
