### ISSUE TITLE
Recherche par cross

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/B2B2C#14]
- Recherche/Recherche.aspx?ref=616024
- On trouve, via les cross une autre pièce, 255303
- C'est confusant pour le client qui peut y voir une erreur.
- Il faudrait signaler par un message "Correspondance trouvée avec 616024"

**Comment by MamboJoel** [comment]
On laisse ce développement en suspend car on ne peut garantir le résultat d'une cross.

**Comment by jlenormant** [comment]
C'est vrai que ce n'est pas très clair, d'ailleurs le résultat peut être une cross avec une référence partielle (on pourrait avoir une pièce xyz qui crosse avec une référence AA**616024**ZZ), donc une référence complètement différente.
