### ISSUE TITLE
Modification logo 6 février 2017

### ISSUE THREAD

**Issue by jlenormant** [groupe-gac/B2B2C#36]

**Comment by jlenormant** [comment]
attention : ne pas mettre en ligne tout de suite

**Comment by jlenormant** [comment]
note : penser à modifier le favicon à la mise en ligne

**Comment by jlenormant** [comment]
voir aussi remplacement /img/epluss.gif dans /Commandes/fax.aspx (+ le .vb, + faxSDPV.aspx s'il est utilisé)

**Comment by MamboJoel** [comment]
Aussi, il y aura des changements de noms de domaine. B2B répondra à client.force-reseau-ps.com.
Il y aura par ailleurs des adresses mails pour ces domaines, et l'on abandonnera les anciennes adresses sdpv.com.

En conséquence si l'application B2B édite des documents à imprimer (bons de commande ou autre) le changement d'image prévu le 6 février impliquera aussi un changement dans les entêtes et pieds de page.

J'ai le cas aussi avec FleetOne (qui répondra à client.force-reseau.gp.com).
