### ISSUE TITLE
reporting : pouvoir regrouper les ventes de pièces par distributeur

### ISSUE THREAD

**Issue by jlenormant** [groupe-gac/B2B2C#8]
dans http://rep.sdpv.com/Reporting/SynthesePieces.aspx
Willy voudrait pouvoir aggréger les chiffres par distributeur (tous les ASVI, tous les IDCF, etc)

**Comment by jlenormant** [comment]
@MamboJoel c'est Jacques qui s'occupe de ce projet ? Je n'ai pas la source.

**Comment by MamboJoel** [comment]
Oui. Je l'assigne.

**Comment by meillere** [comment]
Je regarde le problème mais à l'origine la table des distributeurs avait été crée dans un but totalement inverse de répartir les franchisés sur un ensemble de distributeurs d'une même marque et non d'agglomérer les CA de plusieurs marques.

**Comment by meillere** [comment]
Je vais m'en tirer en passant par la table des comptes fournisseurs de Sage
