### ISSUE TITLE
Franco

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/B2B2C#9]
Ajouter une option "frais réels".

- On paramètre le franco dans Franchise/Client.aspx
- On souhaite mettre une valeur vide (`null`) dans la case "Montant du franco'
- Alors le transport se fera au frais réel.
- Spécifier cette option dans ce formulaire.
- Le préciser dans le bon de commande.

**Comment by jlenormant** [comment]
Vu aujourd'hui :

dans fiche client, faire une coche "frais de port au coût réel". si cochée, griser la case franco et les deux cases frais de port. dans ce cas à la place des frais de transport il faudra afficher (dans la page commande et dans le BL) "frais de port au coût réel"

sinon, le franco atteint supprime la participation aux frais de port à l'achat (preparation HT)
